return {
    -- "nvim-tree/nvim-tree.lua",
    -- version = "*",
    -- -- lazy = false,
    -- cmd = { "NvimTreeToggle" },
    -- -- dependencies = {
    -- --     "nvim-tree/nvim-web-devicons",
    -- -- },
    -- config = function()
    --     require("nvim-tree").setup({
    --         update_focused_file = {
    --             enable = true, -- Habilita la actualización del archivo enfocado
    --             -- update_cwd = true, -- Cambia el directorio de trabajo según el archivo
    --             -- update_root = true,
    --             -- ignore_list = {}, -- Puedes agregar archivos a ignorar si lo deseas
    --         },
    --         -- sync_root_with_cwd = true,
    --         renderer = {
    --             -- icons = {
    --             --     show = {
    --             --         git = true, -- iconos de estado Git
    --             --         file = true, -- iconos de archivo
    --             --         folder = true, -- **¡Muestra iconos de carpeta!**
    --             --         folder_arrow = true, -- icono de flecha junto a carpetas
    --             --     },
    --             -- },
    --
    --             -- sólo muestra el nombre de la carpeta (basename)
    --             root_folder_label = ":t",
    --         },
    --
    --         view = {
    --             width = 30, -- ancho de la ventana
    --             --     adaptive_size = true, -- ajusta el ancho automáticamente
    --             --     side = "left",
    --         },
    --     })
    -- end,
    -- keys = {
    --     { "<leader>z", "<cmd>NvimTreeToggle %:p:h<CR>", desc = "Toggle NvimTree" },
    -- },
}
